server {
  listen 80;
  server_name store.donelocal.com;
  root /var/www/monorepo/store/public;
  index index.php;
  charset utf-8;
  client_max_body_size 128M;
  access_log  /var/log/nginx/access.log main buffer=16k;
  error_log   /var/log/nginx/error.log;
  location / {
    # Redirect everything that isn't a real file to index.php
    try_files $uri $uri/ /index.php?$query_string;
  }
  location ~ \.php$ {
    fastcgi_split_path_info ^(.+\.php)(/.+)$;
    fastcgi_index   index.php;
    fastcgi_pass    done_php83:9000;
    try_files       $uri =404;
    fastcgi_param   SCRIPT_FILENAME    $document_root$fastcgi_script_name;
    fastcgi_param   SCRIPT_NAME        $fastcgi_script_name;
    include         fastcgi_params;
    include /etc/nginx/snippets/cors.conf;
  }
  location ~ /\.(ht|svn|git) {
    deny all;
  }
}
