[options]
addons_path = /mnt/extra-addons/,/mnt/extra-addons/odoo/community_addons/,/mnt/extra-addons/odoo/done_addons/,/mnt/extra-addons/odoo/oca_addons/account-financial-tools/,/mnt/extra-addons/odoo/oca_addons/account-reconcile,/mnt/extra-addons/odoo/oca_addons/web
db_user = odoo
db_password = odoo17@2023
db_host = db
db_port = 5432
admin_passwd = $pbkdf2-sha512$600000$/9.7935P6Z3Tes.Zs3YuZQ$.AJK8OwXcUw7tIGtZ67N3MDSG9woY37TQGl7B0zfwbFs2NifaBOj5jjus2sh/Y6cM7YRIdiWbilurfI1J1PPBw

